'use strict';
// Opt-in real Chromium/CDP regression. No production hosts or payment requests.
const fs=require('fs'),http=require('http'),cp=require('child_process'),assert=require('assert/strict'),WS=require('/home/polybot/node_modules/ws'),path=require('path');
const out=process.env.X402_EVIDENCE||'/home/polybot/.hermes/cache/scratch/npm-package-refresh-20261008/extension-refresh-evidence';fs.mkdirSync(out,{recursive:true});
const profile='/home/polybot/snap/chromium/common/x402-refresh-'+process.pid,ext=profile+'/extension';fs.mkdirSync(profile,{recursive:true});fs.cpSync(path.resolve(__dirname,'..'),ext,{recursive:true});
const port=19862,debug=19863,requests=[],report={requests,iterations:[],errors:[]};let child,sw,page,popup,browser;
const payload={x402Version:2,resource:{url:'http://127.0.0.1:19862/v2'},accepts:[{scheme:'exact',network:'eip155:8453',amount:'10000',asset:'USDC',payTo:'synthetic',maxTimeoutSeconds:60}]};
const server=http.createServer((q,s)=>{requests.push({url:q.url,cookie:q.headers.cookie||null,referrer:q.headers.referer||null});if(q.url==='/redirect'){s.writeHead(302,{Location:'/destination'});return s.end();}s.writeHead(402,{'Content-Type':'text/html','Set-Cookie':'fixture=secret; Path=/','PAYMENT-REQUIRED':Buffer.from(JSON.stringify(payload)).toString('base64')});s.end('<html>synthetic fixture</html>');});
const pause=()=>new Promise(r=>setTimeout(r,20));
async function until(fn,label){const end=Date.now()+10000;while(Date.now()<end){const x=await fn();if(x)return x;await pause();}throw Error('event deadline: '+label);}
function connect(url){return new Promise((resolve,reject)=>{let id=0;const pending=new Map(),events=[];const ws=new WS(url);ws.on('error',reject);ws.on('open',()=>resolve({events,close:()=>ws.close(),send:(method,params={})=>new Promise((r,j)=>{pending.set(++id,{r,j});ws.send(JSON.stringify({id,method,params}));})}));ws.on('message',b=>{const x=JSON.parse(b);if(x.id){const p=pending.get(x.id);pending.delete(x.id);x.error?p.j(x.error):p.r(x.result);}else events.push(x);});});}
async function ev(c,expression){const r=await c.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
const targets=async()=>await(await fetch('http://127.0.0.1:'+debug+'/json')).json();
async function instrument(){await sw.send('Runtime.enable');await ev(sw,`globalThis.trace=[];for(const name of ['setIcon','setBadgeText','setBadgeBackgroundColor','setTitle']){const native=chrome.action[name].bind(chrome.action);chrome.action[name]=async opts=>{trace.push({kind:name,phase:'start',opts});const r=await native(opts);trace.push({kind:name,phase:'end',opts});return r;};}for(const name of ['onBeforeRequest','onHeadersReceived'])chrome.webRequest[name].addListener(d=>trace.push({kind:name,tabId:d.tabId,url:d.url,status:d.statusCode}),{urls:['http://127.0.0.1/*']},name==='onHeadersReceived'?['responseHeaders']:[]);`);}
async function state(){return ev(sw,`(async()=>{let q;do{q=queue;await q;}while(q!==queue);const t=(await chrome.tabs.query({})).find(t=>t.url?.startsWith('http://127.0.0.1:${port}'));return {id:t.id,info:await status(t.id),badge:await chrome.action.getBadgeText({tabId:t.id}),trace:globalThis.trace};})()`);}
async function navigate(url,reload=false){const count=requests.length,start=page.events.length;await page.send(reload?'Page.reload':'Page.navigate',reload?{}:{url});await until(()=>page.events.slice(start).some(e=>e.method==='Page.loadEventFired'),'navigation load');await until(()=>requests.length>count,'fixture request');await until(()=>ev(sw,`trace.some(e=>e.kind==='onHeadersReceived'&&e.url===${JSON.stringify(url)})`),'native headers');return state();}
(async()=>{await new Promise(r=>server.listen(port,'127.0.0.1',r));child=cp.spawn('/snap/bin/chromium',['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking','--disable-component-update','--no-first-run','--disable-sync','--proxy-server=http://127.0.0.1:9','--proxy-bypass-list=127.0.0.1;localhost','--remote-debugging-address=127.0.0.1','--remote-debugging-port='+debug,'--user-data-dir='+profile,'--disable-extensions-except='+ext,'--load-extension='+ext,'about:blank'],{stdio:['ignore',fs.openSync(out+'/chromium.log','w'),fs.openSync(out+'/chromium-errors.log','w')]});const list=await until(async()=>{try{const ts=await targets();return ts.some(t=>t.type==='service_worker')&&ts;}catch{}},'MV3 startup');const worker=list.find(t=>t.type==='service_worker');sw=await connect(worker.webSocketDebuggerUrl);page=await connect(list.find(t=>t.type==='page').webSocketDebuggerUrl);await page.send('Page.enable');await page.send('Network.enable');await page.send('Network.setCacheDisabled',{cacheDisabled:true});await instrument();
const url='http://127.0.0.1:'+port+'/v2?token=hidden';for(let i=0;i<20;i++){await ev(sw,'trace.length=0');const s=await navigate(url,i>0);report.iterations.push(s);assert.equal(s.info.version,2);assert.equal(s.badge,'x402','settled refresh badge');}report.refresh='PASS';
// Deterministic observer race: preserve native API call, gate completion only.
await ev(sw,`globalThis.gate=new Promise(r=>globalThis.release=r);globalThis.gated=false;const native=chrome.action.setIcon;chrome.action.setIcon=async opts=>{const result=await native(opts);if(opts.tabId&&opts.path[16].includes('-active')){gated=true;await gate;}return result;};`);await page.send('Page.reload');await until(()=>ev(sw,'gated'),'native icon completion gate');report.midwrite=await ev(sw,`(async()=>{const t=(await chrome.tabs.query({})).find(t=>t.url?.startsWith('http://127.0.0.1:${port}'));return {info:await status(t.id),badge:await chrome.action.getBadgeText({tabId:t.id})};})()`);assert.equal(report.midwrite.info,null,'Do not publish observed requirements before native badge finishes');assert.equal(report.midwrite.badge,'OFF');await ev(sw,'release()');assert.equal((await state()).badge,'x402');report.observerRace='PASS: requirements remain unpublished until native badge completes';
// Actual MV3 stop/start via browser CDP; wake using extension messaging.
const browserInfo=await(await fetch('http://127.0.0.1:'+debug+'/json/version')).json();browser=await connect(browserInfo.webSocketDebuggerUrl);await page.send('ServiceWorker.enable');await until(()=>page.events.some(e=>e.method==='ServiceWorker.workerVersionUpdated'),'worker version');const versions=page.events.filter(e=>e.method==='ServiceWorker.workerVersionUpdated').flatMap(e=>e.params.versions);const version=versions.reverse().find(v=>v.scriptURL===worker.url&&v.runningStatus==='running');assert.ok(version,'running worker version');
const pt=await(await fetch('http://127.0.0.1:'+debug+'/json/new?'+worker.url.replace('/background.js','/popup.html'),{method:'PUT'})).json();popup=await connect(pt.webSocketDebuggerUrl);await popup.send('Page.enable');await until(()=>ev(popup,"document.readyState==='complete'"),'popup load');const tabId=(await state()).id;sw.close();await page.send('ServiceWorker.stopWorker',{versionId:version.versionId});await ev(popup,`chrome.runtime.sendMessage({type:'GET_TAB_STATUS',tabId:${tabId}})`);const restarted=await until(async()=>(await targets()).find(t=>t.type==='service_worker'&&t.url===worker.url),'restarted target');sw=await connect(restarted.webSocketDebuggerUrl);await instrument();report.restart=await state();assert.equal(report.restart.info.version,2);assert.equal(report.restart.badge,'x402');
// Synthetic extension-page button activation with real native JS consent dialogs.
await ev(popup,`currentTabId=${tabId};currentUrl=${JSON.stringify(url)};`);
report.consent=[];for(const accept of [false,true]){const count=requests.length,start=popup.events.length;const click=popup.send('Runtime.evaluate',{expression:"document.querySelector('#btn-probe').click()"});await until(()=>popup.events.slice(start).some(e=>e.method==='Page.javascriptDialogOpening'),'native consent dialog');await popup.send('Page.handleJavaScriptDialog',{accept});await click;await until(()=>ev(popup,"!document.querySelector('#btn-probe').disabled"),'probe button complete');assert.equal(requests.length,count+(accept?1:0));if(accept){assert.equal(requests.at(-1).cookie,null);assert.equal(requests.at(-1).referrer,null);}report.consent.push({accept,requests:requests.length-count});}
// Explicit probe sends neither seeded cookie nor referrer; redirects never replay.
const before=requests.length;report.probe=await ev(popup,`chrome.runtime.sendMessage({type:'PROBE_URL',tabId:${tabId},url:${JSON.stringify(url)}})`);assert.equal(report.probe.result.version,2);assert.equal(requests.length,before+1);assert.equal(requests.at(-1).cookie,null);assert.equal(requests.at(-1).referrer,null);assert.ok(requests.slice(0,before).some(r=>r.cookie),'seeded browser cookie was exercised');
await ev(sw,'trace.length=0');await navigate('http://127.0.0.1:'+port+'/redirect');const n=requests.filter(r=>r.url==='/destination').length;const current='http://127.0.0.1:'+port+'/destination';// Explicitly point tab back at redirect without navigating by History API.
await ev(page,`history.replaceState({},'', '/redirect')`);const redirect=await ev(popup,`chrome.runtime.sendMessage({type:'PROBE_URL',tabId:${tabId},url:'http://127.0.0.1:${port}/redirect'})`);assert.equal(redirect.result,null);assert.equal(requests.filter(r=>r.url==='/destination').length,n);report.redirect='PASS';report.storage=await ev(sw,'chrome.storage.session.get(null)');assert.ok(!JSON.stringify(report.storage).includes('hidden'));report.errors=sw.events.filter(e=>e.method==='Runtime.exceptionThrown');assert.equal(report.errors.length,0);report.result='PASS';console.log(JSON.stringify({result:report.result,refresh:report.refresh,observerRace:report.observerRace,restart:report.restart.badge,probe:'PASS',redirect:report.redirect}));})().catch(e=>{report.failure=String(e.stack||e);console.error(e);process.exitCode=1;}).finally(()=>{fs.writeFileSync(out+'/runtime.json',JSON.stringify(report,null,2));for(const c of [sw,page,popup,browser])c?.close();child?.kill('SIGTERM');server.close();setTimeout(()=>process.exit(process.exitCode||0),500);});
