name = "x402-check-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
MAX_BATCH_SIZE = "10"
RATE_LIMIT_PER_DAY = "100"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "b7476415792e4e0a9bbc007bd61dda5b"
preview_id = "0b7cf9cedacb44109e37b0d9bc2db05a"

[dev]
port = 8787
local_protocol = "http"
